from setuptools import setup, find_packages

setup(
    name="cryptocurrency-matching-engine",
    version="1.0.0",
    description="High-performance cryptocurrency matching engine with REG NMS compliance",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "flask>=2.3.3",
        "flask-cors>=4.0.0",
        "websockets>=11.0.3",
        "numpy>=1.24.3",
        "pandas>=2.0.3",
        "pytest>=7.4.2",
        "pytest-asyncio>=0.21.1",
        "pytest-cov>=4.1.0",
        "pytest-benchmark>=4.0.0",
        "psutil>=5.9.5",
        "memory-profiler>=0.61.0",
        "python-dateutil>=2.8.2",
        "pydantic>=2.3.0",
        "click>=8.1.7",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
